# Generated by Django 3.0.7 on 2020-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200609_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='liker',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='liker',
            unique_together=set(),
        ),
    ]
