# Generated by Django 3.0 on 2020-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(max_length=500, upload_to='media/images/profile_picture'),
        ),
    ]
