# Generated by Django 3.0 on 2021-02-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_githubprofile_githubrepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
